name = "IterationControl"
uuid = "b3c1a2ee-3fec-4384-bf48-272ea71de57c"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.3.3"

[deps]
EarlyStopping = "792122b4-ca99-40de-a6bc-6742525f08b6"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
EarlyStopping = "0.1.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
